{
 "title": "Simple Observability Dashboard",
 "tags": [
  "nodejs",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Per Second (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(route)(rate(http_requests_total[5m])) * 60",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "QOS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "100 * sum by (instance) (rate(http_requests_total{status=\"200\"}[5m])) / sum by (instance) (rate(http_requests_total[5m]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "Active Partners",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "active_partners_current", "legendFormat": "Partners" }
   ]
  },
  {
   "title": "Average Latency (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by(route)(rate(http_request_duration_seconds_sum[5m])) / sum by(route)(rate(http_request_duration_seconds_count[5m]))) or on() vector(0)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "P95 Latency (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"node-service\"}"
    }
   ]
  }
 ]
}