global:
  resolve_timeout: 5m
route:
  receiver: 'default'
receivers:
  - name: 'default'
    email_configs: []
    slack_configs: []
    webhook_configs: []
    # Add your notification configs here
inhibit_rules: []
